import type { PlaceSchedule } from '../types';
import { CLEANING_PLACES } from '../data/schedule';
import { isGenerated } from '../lib/schedule';
import { PageHeader } from '../components/PageHeader';
import { Section } from '../components/Section';
import { EmptyState } from '../components/EmptyState';
import { Icon } from '../components/Icon';

interface CleaningPageProps {
  schedule: PlaceSchedule;
  onGenerate: () => void;
  canEdit: boolean; // admin or dorm head
  dorm: string;
}

// Cleaning Schedule service page. One "Generate Schedule" button assigns every
// student to exactly one place, spread evenly; the result is shown as a table.
export function CleaningPage({ schedule, onGenerate, canEdit, dorm }: CleaningPageProps) {
  const generated = isGenerated(schedule);
  const totalAssigned = Object.values(schedule).reduce((n, names) => n + names.length, 0);

  return (
    <div>
      <PageHeader
        title="Cleaning Schedule"
        subtitle={`Weekly cleaning assignments for ${dorm}.`}
        action={
          canEdit && (
            <button
              onClick={onGenerate}
              className="inline-flex items-center gap-2 rounded-lg bg-navy px-5 py-2.5 text-sm font-medium text-white transition hover:bg-navy-dark"
            >
              <Icon name="refresh" className="h-4 w-4" />
              {generated ? 'Re-generate Schedule' : 'Generate Schedule'}
            </button>
          )
        }
      />

      <Section>
        {!generated ? (
          canEdit ? (
            <EmptyState text='No schedule yet. Click "Generate Schedule" to assign every student to a cleaning place.' />
          ) : (
            <EmptyState text="No cleaning schedule has been generated yet." />
          )
        ) : (
          <div className="overflow-hidden rounded-xl border border-slate-200">
            <table className="w-full text-left text-sm">
              <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-3 font-semibold">Place</th>
                  <th className="px-4 py-3 font-semibold">Assigned students</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {CLEANING_PLACES.map((place) => {
                  const names = schedule[place] ?? [];
                  return (
                    <tr key={place} className="align-top">
                      <td className="whitespace-nowrap px-4 py-3 font-medium text-slate-800">
                        <span className="inline-flex items-center gap-2">
                          <Icon name="broom" className="h-4 w-4 text-navy" />
                          {place}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex flex-wrap gap-1.5">
                          {names.map((name) => (
                            <span
                              key={name}
                              className="rounded-full bg-navy/5 px-2.5 py-1 text-navy"
                            >
                              {name}
                            </span>
                          ))}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {generated && (
          <p className="mt-4 text-xs text-slate-400">
            {totalAssigned} student{totalAssigned !== 1 ? 's' : ''} assigned across{' '}
            {CLEANING_PLACES.length} places · each student appears exactly once.
            {canEdit && ' Click Re-generate for a fresh assignment.'}
          </p>
        )}
      </Section>

      {!canEdit && (
        <p className="mt-3 text-xs text-slate-400">
          The schedule is generated by the dorm head or admin. You can view your assignment here.
        </p>
      )}
    </div>
  );
}
